### ISSUE TITLE
how to get pretrained model and smpl_related data?

### ISSUE THREAD

**Issue by huangyuan2020** [psyai-net/D-IF_release#1]
I try to excute the demo by

`python -m apps.infer -cfg ./configs/d_if.yaml -gpu 0 -in_dir ./examples -out_dir ./results -export_video -loop_smpl 100 -loop_cloth 200 -hps_type pixie`

but I got `FileNotFoundError: [Errno 2] No such file or directory: '/data/yangxueting/ICON_orl/data/smpl_related/smpl_data/smplx_faces.npy'`

Could you give me more instructions about how to test your method in custom data?

**Comment by yxt7979** [comment]
Hi, thanks for your interest! The smpl_related models should follow the steps in [ICON](https://github.com/YuliangXiu/ICON/blob/master/docs/installation.md#downloading-required-models-and-extra-data) to download the required smpl-(X) models and extra data. 

After following the installation.md, you should replace the ICON model with D-IF model to fit the D-IF network.
The pretrained model has been uploaded to [Google Cloud Drive](https://drive.google.com/file/d/1_JbMMdl-c3I3KbWulAiOUeILPAX1OB5o/view?usp=sharing), you could found it in [readme.md](https://github.com/psyai-net/D-IF_release/blob/main/readme.md).
