### ISSUE TITLE
Query for Visualization Code

### ISSUE THREAD

**Issue by AnderDong** [psyai-net/D-IF_release#3]
Thank you for your amazing work! I would like to render the origin front view and the golden rotated view just like the Fig.4 of the paper. Would it be possible for you to share the code you use for rendering the reconstructed 3D human meshes? This would greatly enhance the quality of visualizations of our work. Appreciate your consideration of this request.

**Comment by yxt7979** [comment]
Hiii, thanks for your interest!

We use MeshLab for visualization, you can download it [here](https://www.meshlab.net/#download). After dragging the 3D Mesh into Meshlab, you can select a color from the Render list.

**Comment by YuliangXiu** [comment]
@AnderDong Please check [ECON issues#32](https://github.com/YuliangXiu/ECON/issues/32#issuecomment-1474855939) to know the detailed procedure to create Fig.4 with golden color.
