### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by xiangli93** [psyai-net/D-IF_release#5]
![image](https://github.com/psyai-net/D-IF_release/assets/79239875/7c1917fa-e69b-48dd-8890-584cf8351c93)
This is the result of my test using the pre-trained model and source code you provided, and it looks quite rough.

**Comment by Dragon2938734** [comment]
can you share you data files structure? i always meet the error:

  File "/home/ssl/autodl-tmp/D-IF_release/apps/infer.py", line 393, in <module>
    verts_pr, faces_pr, _ = model.test_single(in_tensor)
  File "/home/ssl/autodl-tmp/D-IF_release/apps/ICON.py", line 697, in test_single
    verts_pr, faces_pr = self.reconEngine.export_mesh(sdf)
  File "/home/ssl/autodl-tmp/D-IF_release/lib/common/seg3d_lossless.py", line 559, in export_mesh
    final = occupancys[1:, 1:, 1:].contiguous()
TypeError: 'NoneType' object is not subscriptable

i wonder if i made wrong data file structure or did not replace the icon model to d-if model correctly like the author said in the closed issue.

**Comment by xiangli93** [comment]
you need to add the trained model.

**Comment by Dragon2938734** [comment]
yeah，i have add the checkpoint downloaded from the link (29M) and put it in the path 
D-IF_release/data/yangxueting/D_IF_opensource/data/ckpt/d_if/final.ckpt
but still meet that error.

**Comment by xiangli93** [comment]
resume_path: "/data/yangxueting/D_IF_opensource/data/ckpt/d_if/final.ckpt"   


Check that your pre-trained model read in correctly

**Comment by 1211186431** [comment]
> ![image](https://user-images.githubusercontent.com/79239875/273444896-7c1917fa-e69b-48dd-8890-584cf8351c93.png) This is the result of my test using the pre-trained model and source code you provided, and it looks quite rough.

I've noticed that my results are quite similar to yours. Might you have identified the cause? Additionally, I'm curious if you've had a chance to train on the provided dataset and if so, did you find that the outcomes surpassed those from the pre-trained model

**Comment by Dragon2938734** [comment]
<img width="203" alt="屏幕截图 2023-10-09 213336" src="https://github.com/psyai-net/D-IF_release/assets/119784366/57b8842c-35fb-4a2c-b1ea-9f32ec6cbd08">

i change the -hps_type argument from pixie to pymaf , and got the result as above.

**Comment by xiangli93** [comment]
> h



> <img alt="屏幕截图 2023-10-09 213336" width="203" src="https://user-images.githubusercontent.com/119784366/273601461-57b8842c-35fb-4a2c-b1ea-9f32ec6cbd08.png">
> i change the -hps_type argument from pixie to pymaf , and got the result as above.

What files did you change? I change the -hps_type argument from pixie to pymaf, but the result is not as good as yours

**Comment by xiangli93** [comment]
Why "mesh_refine" is bad ?

**Comment by Dragon2938734** [comment]
The only difference maybe that i download the pymaf related data (PyMAF_model_checkpoint.pt/UV_data/mesh_downsampling.npz) from https://github.com/HongwenZhang/PyMAF ,because i cannot get them through the shell script in ICON.

**Comment by yxt7979** [comment]
> ![image](https://user-images.githubusercontent.com/79239875/273444896-7c1917fa-e69b-48dd-8890-584cf8351c93.png) This is the result of my test using the pre-trained model and source code you provided, and it looks quite rough.

Hi! Thanks for your interest. Remember to change the path of normal.ckpt in d-if.yaml under the config folder. Some of my friends met the same problem, after loading the normal.ckpt, it works.

**Comment by xiangli93** [comment]
I have no normal.ckpt。

**Comment by yxt7979** [comment]
> I have no normal.ckpt。

It's the pretrained normal model from our baseline ICON. After you download the pretrained models from [fetch_data.sh](https://github.com/YuliangXiu/ICON/blob/master/docs/installation.md#downloading-required-models-and-extra-data) in ICON, you will find the normal.ckpt (the green arrow). Then you can change the path and load it in.

![mmexport1697090026390](https://github.com/psyai-net/D-IF_release/assets/62125435/3d93115a-b878-41cc-8a42-7bf13576931f)

**Comment by glorioushonor** [comment]
> > ![image](https://user-images.githubusercontent.com/79239875/273444896-7c1917fa-e69b-48dd-8890-584cf8351c93.png) This is the result of my test using the pre-trained model and source code you provided, and it looks quite rough.
> 
> I've noticed that my results are quite similar to yours. Might you have identified the cause? Additionally, I'm curious if you've had a chance to train on the provided dataset and if so, did you find that the outcomes surpassed those from the pre-trained model

Could you please show your quantitive result using the pre-trained model, because I find the result is quiet different from the result in the paper.
Here is mine.
![image](https://github.com/psyai-net/D-IF_release/assets/120625228/4c776325-c571-4e61-99ca-c4df1a24ee52)
