### ISSUE TITLE
Questions about result of test

### ISSUE THREAD

**Issue by glorioushonor** [psyai-net/D-IF_release#6]
Good job. I have some questions to ask in the processing of test. After loading the pre-trained model you provided and the pre-trained model 'normal' from ICON, I ran the test code and obtained the test data. 
`CUDA_VISIBLE_DEVICES=3 python -m apps.train -cfg ./configs/train/d_if.yaml -test`
However, the data I obtained differs from the data shown in your article.  (I only added the pre-trained model and made some file path modifications, but made no other changes.)  
 
![image](https://github.com/psyai-net/D-IF_release/assets/120625228/92e7177a-f3b2-4708-b5ec-f5b3aad08b17)
The organized data is as follows:
![image](https://github.com/psyai-net/D-IF_release/assets/120625228/f9710ecc-2b49-4947-b340-a48e1aa67fec)
I would like to know if this difference is normal, or if the model provided is not the optimal model you obtained?

**Comment by YuliangXiu** [comment]
@yxt7979

**Comment by yxt7979** [comment]
> Good job. I have some questions to ask in the processing of test. After loading the pre-trained model you provided and the pre-trained model 'normal' from ICON, I ran the test code and obtained the test data. `CUDA_VISIBLE_DEVICES=3 python -m apps.train -cfg ./configs/train/d_if.yaml -test` However, the data I obtained differs from the data shown in your article. (I only added the pre-trained model and made some file path modifications, but made no other changes.)
> 
> ![image](https://user-images.githubusercontent.com/120625228/274588484-92e7177a-f3b2-4708-b5ec-f5b3aad08b17.png) The organized data is as follows: ![image](https://user-images.githubusercontent.com/120625228/274593517-f9710ecc-2b49-4947-b340-a48e1aa67fec.png) I would like to know if this difference is normal, or if the model provided is not the optimal model you obtained?

Thank you for your interest! The results are not normal and the final.ckpt is the right model. There is usually a slight deviation in the indicator results, but not this big. Please check: Is your environment correct? You can firstly try testing our baseline ICON to see if you have the same results?

**Comment by glorioushonor** [comment]
> > Good job. I have some questions to ask in the processing of test. After loading the pre-trained model you provided and the pre-trained model 'normal' from ICON, I ran the test code and obtained the test data. `CUDA_VISIBLE_DEVICES=3 python -m apps.train -cfg ./configs/train/d_if.yaml -test` However, the data I obtained differs from the data shown in your article. (I only added the pre-trained model and made some file path modifications, but made no other changes.)
> > ![image](https://user-images.githubusercontent.com/120625228/274588484-92e7177a-f3b2-4708-b5ec-f5b3aad08b17.png) The organized data is as follows: ![image](https://user-images.githubusercontent.com/120625228/274593517-f9710ecc-2b49-4947-b340-a48e1aa67fec.png) I would like to know if this difference is normal, or if the model provided is not the optimal model you obtained?
> 
> Thank you for your interest! The results are not normal and the final.ckpt is the right model. There is usually a slight deviation in the indicator results, but not this big. Please check: Is your environment correct? You can firstly try testing our baseline ICON to see if you have the same results?

@yxt7979 @YuliangXiu Thank you for your kind response. I have done my best to investigate the issue, but haven't made any progress. Therefore, I am planning to try training on my own and then examine the test results. However, during the training process, I encountered the following issues:

1. The training loss remained at 0, and I found that [a line of code](https://github.com/psyai-net/D-IF_release/blob/main/apps/ICON.py#L217) was causing the loss to be 0. I managed to train normally by commenting out this line of code. I am unsure if my action was correct.
   
2. The training loss during the process seems to be inconsistent with the description in the paper. According to [the code](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L411) , the final loss is **Lun = _Lrec_ + 0.5Ldis**, while in the paper, it is **Lun = Ldis + _0.55Lrec_**. Additionally, [the value of β](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L409) is inconsistent with the paper, where β = 4.

**Comment by yxt7979** [comment]
> > > Good job. I have some questions to ask in the processing of test. After loading the pre-trained model you provided and the pre-trained model 'normal' from ICON, I ran the test code and obtained the test data. `CUDA_VISIBLE_DEVICES=3 python -m apps.train -cfg ./configs/train/d_if.yaml -test` However, the data I obtained differs from the data shown in your article. (I only added the pre-trained model and made some file path modifications, but made no other changes.)
> > > ![image](https://user-images.githubusercontent.com/120625228/274588484-92e7177a-f3b2-4708-b5ec-f5b3aad08b17.png) The organized data is as follows: ![image](https://user-images.githubusercontent.com/120625228/274593517-f9710ecc-2b49-4947-b340-a48e1aa67fec.png) I would like to know if this difference is normal, or if the model provided is not the optimal model you obtained?
> > 
> > 
> > Thank you for your interest! The results are not normal and the final.ckpt is the right model. There is usually a slight deviation in the indicator results, but not this big. Please check: Is your environment correct? You can firstly try testing our baseline ICON to see if you have the same results?
> 
> @yxt7979 @YuliangXiu Thank you for your kind response. I have done my best to investigate the issue, but haven't made any progress. Therefore, I am planning to try training on my own and then examine the test results. However, during the training process, I encountered the following issues:
> 
> 1. The training loss remained at 0, and I found that [a line of code](https://github.com/psyai-net/D-IF_release/blob/main/apps/ICON.py#L217) was causing the loss to be 0. I managed to train normally by commenting out this line of code. I am unsure if my action was correct.
> 2. The training loss during the process seems to be inconsistent with the description in the paper. According to [the code](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L411) , the final loss is **Lun = _Lrec_ + 0.5Ldis**, while in the paper, it is **Lun = Ldis + _0.55Lrec_**. Additionally, [the value of β](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L409) is inconsistent with the paper, where β = 4.

Thanks for your effort! 
1. This line should be commented, and I use this line to test for uncertainty. You are right.
2. The setting of the hyperparameter in the article is the best version we tried when using, a slight change will not have much impact, you can choose the hyperparameter in the article.

I very suggest you firstly train without smooth occupancy and the uncertainty loss. You can change it [here](https://github.com/psyai-net/D-IF_release/blob/main/lib/dataset/PIFuDataset.py#L619).
use 
`sdf_labels = labels`
instead and comment the uncertainty loss.

Be careful with the training strategy：
1. firstly, use the only mse(gt, final pred occ)
2. then refine the model with mse(gt, final pred occ) + mse(gt, pred distribution miu)
for these two stages, you can change the loss [here](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L386)

**Comment by glorioushonor** [comment]
> > > > Good job. I have some questions to ask in the processing of test. After loading the pre-trained model you provided and the pre-trained model 'normal' from ICON, I ran the test code and obtained the test data. `CUDA_VISIBLE_DEVICES=3 python -m apps.train -cfg ./configs/train/d_if.yaml -test` However, the data I obtained differs from the data shown in your article. (I only added the pre-trained model and made some file path modifications, but made no other changes.)
> > > > ![image](https://user-images.githubusercontent.com/120625228/274588484-92e7177a-f3b2-4708-b5ec-f5b3aad08b17.png) The organized data is as follows: ![image](https://user-images.githubusercontent.com/120625228/274593517-f9710ecc-2b49-4947-b340-a48e1aa67fec.png) I would like to know if this difference is normal, or if the model provided is not the optimal model you obtained?
> > > 
> > > 
> > > Thank you for your interest! The results are not normal and the final.ckpt is the right model. There is usually a slight deviation in the indicator results, but not this big. Please check: Is your environment correct? You can firstly try testing our baseline ICON to see if you have the same results?
> > 
> > 
> > @yxt7979 @YuliangXiu Thank you for your kind response. I have done my best to investigate the issue, but haven't made any progress. Therefore, I am planning to try training on my own and then examine the test results. However, during the training process, I encountered the following issues:
> > 
> > 1. The training loss remained at 0, and I found that [a line of code](https://github.com/psyai-net/D-IF_release/blob/main/apps/ICON.py#L217) was causing the loss to be 0. I managed to train normally by commenting out this line of code. I am unsure if my action was correct.
> > 2. The training loss during the process seems to be inconsistent with the description in the paper. According to [the code](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L411) , the final loss is **Lun = _Lrec_ + 0.5Ldis**, while in the paper, it is **Lun = Ldis + _0.55Lrec_**. Additionally, [the value of β](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L409) is inconsistent with the paper, where β = 4.
> 
> Thanks for your effort!
> 
> 1. This line should be commented, and I use this line to test for uncertainty. You are right.
> 2. The setting of the hyperparameter in the article is the best version we tried when using, a slight change will not have much impact, you can choose the hyperparameter in the article.
> 
> I very suggest you firstly train without smooth occupancy and the uncertainty loss. You can change it [here](https://github.com/psyai-net/D-IF_release/blob/main/lib/dataset/PIFuDataset.py#L619). use `sdf_labels = labels` instead and comment the uncertainty loss.
> 
> Be careful with the training strategy：
> 
> 1. firstly, use the only mse(gt, final pred occ)
> 2. then refine the model with mse(gt, final pred occ) + mse(gt, pred distribution miu)
>    for these two stages, you can change the loss [here](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L386)

Thank you for your kind response. However, I have some doubts about the training strategy. If it is as you said, then the KL loss is not being used.
According to the description in the paper and my understanding, shouldn't the training strategy be as follows?

1. Firstly, use the mse(gt, final pred occ) + mse(gt, pred distribution miu),10 epochs
2. Then refine the model with mse(gt, final pred occ) + mse(gt, pred distribution miu) + [KL(·）](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L411)，5 epochs

**Comment by yxt7979** [comment]
> > > > > Good job. I have some questions to ask in the processing of test. After loading the pre-trained model you provided and the pre-trained model 'normal' from ICON, I ran the test code and obtained the test data. `CUDA_VISIBLE_DEVICES=3 python -m apps.train -cfg ./configs/train/d_if.yaml -test` However, the data I obtained differs from the data shown in your article. (I only added the pre-trained model and made some file path modifications, but made no other changes.)
> > > > > ![image](https://user-images.githubusercontent.com/120625228/274588484-92e7177a-f3b2-4708-b5ec-f5b3aad08b17.png) The organized data is as follows: ![image](https://user-images.githubusercontent.com/120625228/274593517-f9710ecc-2b49-4947-b340-a48e1aa67fec.png) I would like to know if this difference is normal, or if the model provided is not the optimal model you obtained?
> > > > 
> > > > 
> > > > Thank you for your interest! The results are not normal and the final.ckpt is the right model. There is usually a slight deviation in the indicator results, but not this big. Please check: Is your environment correct? You can firstly try testing our baseline ICON to see if you have the same results?
> > > 
> > > 
> > > @yxt7979 @YuliangXiu Thank you for your kind response. I have done my best to investigate the issue, but haven't made any progress. Therefore, I am planning to try training on my own and then examine the test results. However, during the training process, I encountered the following issues:
> > > 
> > > 1. The training loss remained at 0, and I found that [a line of code](https://github.com/psyai-net/D-IF_release/blob/main/apps/ICON.py#L217) was causing the loss to be 0. I managed to train normally by commenting out this line of code. I am unsure if my action was correct.
> > > 2. The training loss during the process seems to be inconsistent with the description in the paper. According to [the code](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L411) , the final loss is **Lun = _Lrec_ + 0.5Ldis**, while in the paper, it is **Lun = Ldis + _0.55Lrec_**. Additionally, [the value of β](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L409) is inconsistent with the paper, where β = 4.
> > 
> > 
> > Thanks for your effort!
> > 
> > 1. This line should be commented, and I use this line to test for uncertainty. You are right.
> > 2. The setting of the hyperparameter in the article is the best version we tried when using, a slight change will not have much impact, you can choose the hyperparameter in the article.
> > 
> > I very suggest you firstly train without smooth occupancy and the uncertainty loss. You can change it [here](https://github.com/psyai-net/D-IF_release/blob/main/lib/dataset/PIFuDataset.py#L619). use `sdf_labels = labels` instead and comment the uncertainty loss.
> > Be careful with the training strategy：
> > 
> > 1. firstly, use the only mse(gt, final pred occ)
> > 2. then refine the model with mse(gt, final pred occ) + mse(gt, pred distribution miu)
> >    for these two stages, you can change the loss [here](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L386)
> 
> Thank you for your kind response. However, I have some doubts about the training strategy. If it is as you said, then the KL loss is not being used. According to the description in the paper and my understanding, shouldn't the training strategy be as follows?
> 
> 1. Firstly, use the mse(gt, final pred occ) + mse(gt, pred distribution miu),10 epochs
> 2. Then refine the model with mse(gt, final pred occ) + mse(gt, pred distribution miu) + [KL(·）](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L411)，5 epochs

We only use $L_{rec}$ for the first 10 epochs according to our peper in Section 4, and we use $L_{rec} + L_{dis}$ for the second stage. 

I firstly suggest you use $L_{rec} + L_{mse}$ as using occupancy is better for D-IF being a baseline (it is more accurate for occupancy than sdf). And it's easier for you to try uncertainty loss base on it. 

Thank you.

**Comment by glorioushonor** [comment]
> > > > > > Good job. I have some questions to ask in the processing of test. After loading the pre-trained model you provided and the pre-trained model 'normal' from ICON, I ran the test code and obtained the test data. `CUDA_VISIBLE_DEVICES=3 python -m apps.train -cfg ./configs/train/d_if.yaml -test` However, the data I obtained differs from the data shown in your article. (I only added the pre-trained model and made some file path modifications, but made no other changes.)
> > > > > > ![image](https://user-images.githubusercontent.com/120625228/274588484-92e7177a-f3b2-4708-b5ec-f5b3aad08b17.png) The organized data is as follows: ![image](https://user-images.githubusercontent.com/120625228/274593517-f9710ecc-2b49-4947-b340-a48e1aa67fec.png) I would like to know if this difference is normal, or if the model provided is not the optimal model you obtained?
> > > > > 
> > > > > 
> > > > > Thank you for your interest! The results are not normal and the final.ckpt is the right model. There is usually a slight deviation in the indicator results, but not this big. Please check: Is your environment correct? You can firstly try testing our baseline ICON to see if you have the same results?
> > > > 
> > > > 
> > > > @yxt7979 @YuliangXiu Thank you for your kind response. I have done my best to investigate the issue, but haven't made any progress. Therefore, I am planning to try training on my own and then examine the test results. However, during the training process, I encountered the following issues:
> > > > 
> > > > 1. The training loss remained at 0, and I found that [a line of code](https://github.com/psyai-net/D-IF_release/blob/main/apps/ICON.py#L217) was causing the loss to be 0. I managed to train normally by commenting out this line of code. I am unsure if my action was correct.
> > > > 2. The training loss during the process seems to be inconsistent with the description in the paper. According to [the code](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L411) , the final loss is **Lun = _Lrec_ + 0.5Ldis**, while in the paper, it is **Lun = Ldis + _0.55Lrec_**. Additionally, [the value of β](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L409) is inconsistent with the paper, where β = 4.
> > > 
> > > 
> > > Thanks for your effort!
> > > 
> > > 1. This line should be commented, and I use this line to test for uncertainty. You are right.
> > > 2. The setting of the hyperparameter in the article is the best version we tried when using, a slight change will not have much impact, you can choose the hyperparameter in the article.
> > > 
> > > I very suggest you firstly train without smooth occupancy and the uncertainty loss. You can change it [here](https://github.com/psyai-net/D-IF_release/blob/main/lib/dataset/PIFuDataset.py#L619). use `sdf_labels = labels` instead and comment the uncertainty loss.
> > > Be careful with the training strategy：
> > > 
> > > 1. firstly, use the only mse(gt, final pred occ)
> > > 2. then refine the model with mse(gt, final pred occ) + mse(gt, pred distribution miu)
> > >    for these two stages, you can change the loss [here](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L386)
> > 
> > 
> > Thank you for your kind response. However, I have some doubts about the training strategy. If it is as you said, then the KL loss is not being used. According to the description in the paper and my understanding, shouldn't the training strategy be as follows?
> > 
> > 1. Firstly, use the mse(gt, final pred occ) + mse(gt, pred distribution miu),10 epochs
> > 2. Then refine the model with mse(gt, final pred occ) + mse(gt, pred distribution miu) + [KL(·）](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L411)，5 epochs
> 
> We only use Lrec for the first 10 epochs according to our peper in Section 4, and we use Lrec+Ldis for the second stage.
> 
> I firstly suggest you use Lrec+Lmse as using occupancy is better for D-IF being a baseline (it is more accurate for occupancy than sdf). And it's easier for you to try uncertainty loss base on it.
> 
> Thank you.

Thank you for your patient explanation. However, after listening to your explanation, I am even more confused. I would like to clarify, please let me know if my understanding is correct.

In the code, there are three loss terms: two MSE losses and one KL loss.
1. `error_if += self.error_term(pred_if, occ_labels)`
  This is an MSE loss, corresponding to "Lrec" in the paper.
![image](https://github.com/psyai-net/D-IF_release/assets/120625228/d67c3aa8-faaf-4cf6-9b51-c2ad28863351)

2. `error_if += self.error_term(miu_if, occ_labels)`
  This is also an MSE loss. **I did not find a corresponding loss in the paper.**
3. `error_if += 0.5 * self.univar_continue_KL_divergence2(labels, target_sigma, miu_if, sigma_if).mean()`
  This is a KL loss, corresponding to "Ldis" in the paper.
![image](https://github.com/psyai-net/D-IF_release/assets/120625228/874b0cac-a1a3-4684-826d-87105213b01f)
Thanks very much!

**Comment by yxt7979** [comment]
> > > > > > > Good job. I have some questions to ask in the processing of test. After loading the pre-trained model you provided and the pre-trained model 'normal' from ICON, I ran the test code and obtained the test data. `CUDA_VISIBLE_DEVICES=3 python -m apps.train -cfg ./configs/train/d_if.yaml -test` However, the data I obtained differs from the data shown in your article. (I only added the pre-trained model and made some file path modifications, but made no other changes.)
> > > > > > > ![image](https://user-images.githubusercontent.com/120625228/274588484-92e7177a-f3b2-4708-b5ec-f5b3aad08b17.png) The organized data is as follows: ![image](https://user-images.githubusercontent.com/120625228/274593517-f9710ecc-2b49-4947-b340-a48e1aa67fec.png) I would like to know if this difference is normal, or if the model provided is not the optimal model you obtained?
> > > > > > 
> > > > > > 
> > > > > > Thank you for your interest! The results are not normal and the final.ckpt is the right model. There is usually a slight deviation in the indicator results, but not this big. Please check: Is your environment correct? You can firstly try testing our baseline ICON to see if you have the same results?
> > > > > 
> > > > > 
> > > > > @yxt7979 @YuliangXiu Thank you for your kind response. I have done my best to investigate the issue, but haven't made any progress. Therefore, I am planning to try training on my own and then examine the test results. However, during the training process, I encountered the following issues:
> > > > > 
> > > > > 1. The training loss remained at 0, and I found that [a line of code](https://github.com/psyai-net/D-IF_release/blob/main/apps/ICON.py#L217) was causing the loss to be 0. I managed to train normally by commenting out this line of code. I am unsure if my action was correct.
> > > > > 2. The training loss during the process seems to be inconsistent with the description in the paper. According to [the code](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L411) , the final loss is **Lun = _Lrec_ + 0.5Ldis**, while in the paper, it is **Lun = Ldis + _0.55Lrec_**. Additionally, [the value of β](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L409) is inconsistent with the paper, where β = 4.
> > > > 
> > > > 
> > > > Thanks for your effort!
> > > > 
> > > > 1. This line should be commented, and I use this line to test for uncertainty. You are right.
> > > > 2. The setting of the hyperparameter in the article is the best version we tried when using, a slight change will not have much impact, you can choose the hyperparameter in the article.
> > > > 
> > > > I very suggest you firstly train without smooth occupancy and the uncertainty loss. You can change it [here](https://github.com/psyai-net/D-IF_release/blob/main/lib/dataset/PIFuDataset.py#L619). use `sdf_labels = labels` instead and comment the uncertainty loss.
> > > > Be careful with the training strategy：
> > > > 
> > > > 1. firstly, use the only mse(gt, final pred occ)
> > > > 2. then refine the model with mse(gt, final pred occ) + mse(gt, pred distribution miu)
> > > >    for these two stages, you can change the loss [here](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L386)
> > > 
> > > 
> > > Thank you for your kind response. However, I have some doubts about the training strategy. If it is as you said, then the KL loss is not being used. According to the description in the paper and my understanding, shouldn't the training strategy be as follows?
> > > 
> > > 1. Firstly, use the mse(gt, final pred occ) + mse(gt, pred distribution miu),10 epochs
> > > 2. Then refine the model with mse(gt, final pred occ) + mse(gt, pred distribution miu) + [KL(·）](https://github.com/psyai-net/D-IF_release/blob/main/lib/net/HGPIFuNet.py#L411)，5 epochs
> > 
> > 
> > We only use Lrec for the first 10 epochs according to our peper in Section 4, and we use Lrec+Ldis for the second stage.
> > I firstly suggest you use Lrec+Lmse as using occupancy is better for D-IF being a baseline (it is more accurate for occupancy than sdf). And it's easier for you to try uncertainty loss base on it.
> > Thank you.
> 
> Thank you for your patient explanation. However, after listening to your explanation, I am even more confused. I would like to clarify, please let me know if my understanding is correct.
> 
> In the code, there are three loss terms: two MSE losses and one KL loss.
> 
> 1. `error_if += self.error_term(pred_if, occ_labels)`
>    This is an MSE loss, corresponding to "Lrec" in the paper.
>    ![image](https://user-images.githubusercontent.com/120625228/276180013-d67c3aa8-faaf-4cf6-9b51-c2ad28863351.png)
> 2. `error_if += self.error_term(miu_if, occ_labels)`
>    This is also an MSE loss. **I did not find a corresponding loss in the paper.**
> 3. `error_if += 0.5 * self.univar_continue_KL_divergence2(labels, target_sigma, miu_if, sigma_if).mean()`
>    This is a KL loss, corresponding to "Ldis" in the paper.
>    ![image](https://user-images.githubusercontent.com/120625228/276180644-874b0cac-a1a3-4684-826d-87105213b01f.png)
>    Thanks very much!

yep! the first and third loss that you understand is correct. We use the second loss `error_if += self.error_term(miu_if, occ_labels)` in the repo for the occupancy situation (the easier and more common vision) 
For occupancy, you should Loss1 for 10 epochs, and then Loss1 + Loss2 for 5 epochs (easier to expend).
With the smooth occpancy, you should Loss1 for 10 epochs, and then Loss1 + Loss3 for 5 epochs (reproduce).
