### ISSUE TITLE
Questions about the Cape dataset

### ISSUE THREAD

**Issue by glorioushonor** [psyai-net/D-IF_release#7]
Have you re-rendered the Cape dataset? ICON provides rendered results of 3-views, but in the paper, you mentioned using results of 4-views. IF you have re-rendered the Cape dataset, could you please provide the rendering code?
![image](https://github.com/psyai-net/D-IF_release/assets/120625228/7a9919a6-e0ca-4630-ba77-a2870a88132e)

**Comment by yxt7979** [comment]
Thank you! We evaluation under the same setting as ICON with 3 views (0, 120, 240) and I will update the arXiv later. Thanks for correcting us!
